# Generated by Django 4.2.29 on 2026-03-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedItem',
        ),
    ]
