# Generated by Django 4.2.29 on 2026-04-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_add_terms_accepted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Đăng nhập thành công"),
                            ("login_failed", "Đăng nhập thất bại"),
                            ("login_locked", "Tài khoản bị khóa"),
                            ("register_success", "Đăng ký thành công"),
                            ("register_failed", "Đăng ký thất bại"),
                            ("password_reset", "Đặt lại mật khẩu"),
                            ("email_verified", "Xác minh email"),
                            ("logout", "Đăng xuất"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["event_type", "created_at"], name="users_audit_event_t_9e127e_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["ip_address", "created_at"], name="users_audit_ip_addr_2d2ab3_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["email", "created_at"], name="users_audit_email_ef4d8b_idx"),
        ),
    ]
